name: Publish to NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@wovosoft'
      - name: Install dependencies
        run: npm install
      - name: Building Components and Typings
        run: npm run build
      - name: Executing Publish Script
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run:
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm run publish
